# requirements.yml
---
collections:
  - name: community.general
    version: ">=8.4.0"
  - name: ansible.posix
    version: ">=1.5.0"
  - name: community.docker
    version: ">=3.5.0"

roles:
  - name: geerlingguy.docker
  - name: docker-container-pihole          # ← local role name
    src: https://github.com/emielmolenaar/ansible-role-docker-pihole.git
    scm: git
