---


# 1 ▸ Kernel settings  (NAT needs forwarding)
- import_tasks: sysctl.yml         # ← new

# 2 ▸ Interface configuration
- import_tasks: netplan.yml
- import_tasks: dnsmasq.yml
# 3 ▸ Firewall ruleset
- name: Render nftables.conf
  template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf.new 
    owner: root
    mode: "0644"


- name: Render nftables.conf
  template:
    src: nftables.conf.j2
    dest: /etc/nftables.conf
    owner: root
    mode: "0644"
    validate: "nft -c -f %s"

- name: Reload nftables rules
  command: nft -f /etc/nftables.conf
  become: true

# 4 ▸ Optional QoS
- import_tasks: qos_persist.yml  # Add this line


# roles/firewall/handlers/main.yml
