---
# Deploy the netplan description and bring up the LAN + WAN links
- name: Render netplan configuration for LAN / WAN
  ansible.builtin.template:
    src: netplan.yaml.j2               # already lives in templates/
    dest: /etc/netplan/50-firewall.yaml
    owner: root
    group: root
    mode: "0640"
  vars:
    lan_interface: "{{ firewall_cfg.interfaces.lan.nic }}"
    lan_cidr:      "{{ firewall_cfg.interfaces.lan.cidr }}"
    wan_interface: "{{ firewall_cfg.interfaces.wan.nic }}"
 
- name: Delete the cloud-init Netplan file (if it exists)
  ansible.builtin.file:
    path: /etc/netplan/50-cloud-init.yaml
    state: absent
