- name: Install required packages for nDPI, DKMS, and nftables
  apt:
    name:
      - libndpi4.2
      - libndpi-dev
      - libndpi-bin
      - dkms
      - build-essential
      - git
      - nftables
      - libpcap-dev
      - linux-headers-{{ ansible_kernel }}
      - libpcap-dev
      - libnetfilter-conntrack-dev
      - libtool
      - autoconf
      - automake
      - wget
      - libc6-dev      
    state: present
    update_cache: true

- name: Check if the nDPI {{ ndpi_version }} tarball is already present
  stat:
    path: "/tmp/nDPI-{{ ndpi_version }}.tar.gz"
  register: ndpi_tarball
- name: Download nDPI {{ ndpi_version }} source tarball
  get_url:
    url: "https://github.com/ntop/nDPI/archive/refs/tags/{{ ndpi_version }}.tar.gz"
    dest: "/tmp/nDPI-{{ ndpi_version }}.tar.gz"
    mode: "0644"
    force: no                  # don’t re-download if checksum matches
  when: not ndpi_tarball.stat.exists
  register: ndpi_tar
- name: Extract nDPI sources to /usr/src (idempotent)
  unarchive:
    src:  "/tmp/nDPI-{{ ndpi_version }}.tar.gz"
    dest: /usr/src
    remote_src: yes
    creates: "{{ ndpi_src_dir }}"
- name: Ensure NDPI_PATH is set in dkms.conf
  lineinfile:
    path: "{{ xt_ndpi_src }}/dkms.conf"
    regexp: '^NDPI_PATH='
    line: 'NDPI_PATH="{{ ndpi_src_dir }}"'
    insertafter: '^AUTOINSTALL='

- name: Ensure xt_ndpi source directory exists
  file:
    path: "/usr/src/xt_ndpi-{{ ndpi_version }}"
    state: directory
    mode: "0755"

- name: Clone xt_ndpi source from repository
  git:
    repo: "{{ xt_ndpi_src_repo }}"
    dest: "/usr/src/xt_ndpi-{{ ndpi_version }}"
    version: master
  register: xt_ndpi_src
  tags: xt_ndpi

- name: Drop DKMS configuration into the source tree
  template:
    src: "dkms.conf.j2"
    dest: "/usr/src/xt_ndpi-{{ ndpi_version }}/dkms.conf"
    owner: root
    group: root
    mode: "0644"
  register: dkms_conf

- name: Register xt_ndpi module with DKMS
  command: dkms add -m xt_ndpi -v {{ ndpi_version }}
  args:
    creates: "/var/lib/dkms/xt_ndpi/{{ ndpi_version }}"
  #when: xt_ndpi_src.changed or dkms_conf.changed
  notify: Rebuild xt_ndpi (DKMS)

- name: Install xt_ndpi module via DKMS
  command: dkms install -m xt_ndpi -v {{ ndpi_version }}
  #when: xt_ndpi_src.changed or dkms_conf.changed

- name: Ensure xt_ndpi module loads on boot
  copy:
    dest: /etc/modules-load.d/xt_ndpi.conf
    content: "xt_ndpi\n"
  notify: Load xt_ndpi module

- name: Load xt_ndpi module immediately
  community.general.modprobe:
    name: xt_ndpi
    state: present